# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a89efaf4e7e63897d96984a952a5bf5b01d54b22a742dc61473983a1149b537b512361045d58b4cd25d067e2814e0bb65242a02189abc15a18cd9c20537222bc

test:
  secret_key_base: 155a6065fc7d474e65312d918fa56b0cf8259180d50e35a1864778eb90ac0d3939353bf7a073dbd04259ca16d244c09c7dabccdf2b66a4eedfb1cccfb795eb6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
